### ISSUE TITLE
Simplify dashboard file

### ISSUE THREAD

**Issue by SketchingDev** [SketchingDev/Doodle-Dashboard#9]
At present a dashboard file maps too closely to the implementation, causing it to be difficult to understand for a lay person just wanting to create a simple dashboard i.e. an image notification must declare an updater.

Instead the following structure is much simpler...

```
interval: 5
display: console

data-feeds:
  - source: rss
    url: https://api.travis-ci.org/repos/SketchingDev/Doodle-Dashboard/builds.atom
    sort: oldest

notifications:
  - title: Doodle-Dashboard build status
    type: image-depending-on-message-content
    options:
      default-image: https://raw.githubusercontent.com/SketchingDev/Doodle-Dashboard/examples/build-radiator/images/unknown.png
        images:
        - path: https://raw.githubusercontent.com/SketchingDev/Doodle-Dashboard/examples/build-radiator/images/failure.png
          if-contains: "State: failed"
        - path: https://raw.githubusercontent.com/SketchingDev/Doodle-Dashboard/examples/build-radiator/status-icons/building.png
          if-contains: "State: started"
        - path: https://raw.githubusercontent.com/SketchingDev/Doodle-Dashboard/examples/build-radiator/status-icons/success.png
          if-contains: "State: passed"
    filters:
      - type: message-contains-text
        text: "SketchingDev/Doodle-Dashboard Build"
```
